### ISSUE TITLE
Adding players to a scrum?

### ISSUE THREAD

**Issue by johnkcox** [astroscrum/hubot-astroscrum#3]
Not really an issue but can't figure out how to add players to a scrum. Am I missing something obvious here? Thanks!

**Comment by jpsilvashy** [comment]
@mmcdaris wanna help with this, I think you had this issue when setting up a month ago or so. @johnkcox we'll get this fixed asap, thanks for creating an issue.

**Comment by johnkcox** [comment]
Thanks. And for the record I realize that I am using the "hubot-scrum" script not the "hubot-astroscrum" one. Not sure if that makes a difference but seemed relevant.

**Comment by jpsilvashy** [comment]
Yes, actually that matters, you should be using `hubot-astroscrum`.  But I still think you'll have an issue, its a bit complicated in that you need to watch the logs as the bot boots up, and set set a few ENV based on the output you see. I'm working on fixing this now.

**Comment by jpsilvashy** [comment]
Fixed by: https://github.com/astroscrum/hubot-astroscrum/commit/1f893163810b94e9c8e791244d9b225ead966d2b#diff-752baea5fdd8287131808136f90ffdfdR179
