### ISSUE TITLE
Can't stop getting emails from bot@astroscrum.com

### ISSUE THREAD

**Issue by Bukashk0zzz** [astroscrum/hubot-astroscrum#6]
I deleted hubot and unconnect it from slack. But I still getting emails from bot@astroscrum.com

How I can stop this?

**Comment by Bukashk0zzz** [comment]
Also you have slack #help chanel but it closed.

<img width="288" alt="screen shot 2015-11-11 at 10 30 38" src="https://cloud.githubusercontent.com/assets/1908342/11087006/4c0a7736-885f-11e5-8301-000bc134ad12.png">

**Comment by jpsilvashy** [comment]
damn, we better clean up our act, sorry about the mess. :-/

**Comment by Bukashk0zzz** [comment]
Thanks. Now emails stopped coming.
